# Generated by Django 5.2 on 2025-04-30 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('done', 'Done'), ('not_done', 'Not Done'), ('in_work', 'In Work')], default='not_done', max_length=10)),
            ],
        ),
    ]
